### ISSUE TITLE
Error - unauthorized_client

### ISSUE THREAD

**Issue by komangss** [Eagnir/GmailNotify-PubSub-GCP#3]
I have got error when i try to get authenticated gmail. 
here is the error description :
"Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."

what have i done : 
using service account and generate json for it and change appconfig->gcp.auth.googleKeyFilePath to service account's json path that have been generated.

**Comment by Eagnir** [comment]
**Kindly note, you can't use a service account with a normal gmail account (email ending with @gmail.com), service account needs pre authorization which is only possible if you are using GSuite (now known as Google Workspace).**

The error indicates that the service account that you have (or created) might not have permission for the GCP project.

**To confirm, you can**
1) Login to GCP Console
2) Navigate to your project
3) Navigate to IAM & Admin > Service Accounts

**Verify the following**
1) The email has a green check mark under status column. This email should match the email in your googleKeyFile > "client_email" property.
2) The Key ID for this email should match the key id in your googleKeyFile > "private_key_id" property.
3) The OAuth 2 Client ID for this email should match the client id in your googleKeyFile > "client_id" property.

If the above is corrected and verified, please share the permissions you assigned for this service account for this project.

I am assuming you get this error while calling the StartWatch function for the first time.

**Comment by komangss** [comment]
Thanks for your reply, I think it is beacause im using gmail account to create service account

**Comment by komangss** [comment]
What permission is needed to create a service account?
I'm using the Storage Object Admin role, to access the storage.
but I got
`Error: unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.`
When getAuthenticatedGmail.

**Comment by komangss** [comment]
I also already set domain-wide delegation with id, and still, get that error

**Comment by Eagnir** [comment]
@komangss 
You need to create the Service Account via "IAM & Admin > Service Account" section via the website. The role required for this service account is "Cloud Functions Service Agent". Ensure you grant access to your project where you are deploying this code.

Be careful setting the domain-wide delegation. It is not required for this project. If you don't need it explicitly, It is highly recommended to keep it disabled.

**Comment by Eagnir** [comment]
Closing the issue due to inactivity.
